---
title: "PoissonVariance"
output: html_document
---


```{r}
library(ggplot2)
library(stringr)
library(dplyr)
library(knitr)
library(reshape2)
opts_chunk$set(fig.width = 10,fig.height = 5,cache=F)
```

#Read in posteriors from each dispersion

```{r}
parfiles<-list.files("Dispersion",full.names = T,pattern="Allpars*")
pf<-lapply(parfiles,read.csv,row.names=1)

names(pf)<-  sapply(parfiles,function(x) {str_extract(x,"\\d+")})

names(pf)[1]<-0.5

#name by dispersion
for (x in 1:length(pf)){
  pf[[x]]$Dispersion<-as.numeric(names(pf)[[x]])
}

dat<-rbind_all(pf)
```

# View convergence

## Slope and Intercept

```{r}
ggplot(dat[dat$par %in% c("intercept","gamma"),],aes(x=Draw,y=estimate,col=as.factor(Dispersion))) + geom_line() + facet_wrap(~par,ncol=1,scales="free")
```

## Detection
```{r}
ggplot(dat[dat$par %in% c("detect"),],aes(x=Draw,y=estimate,col=as.factor(Dispersion))) + geom_line() + facet_wrap(~species,ncol=2,scales="free") + labs(fill="Dispersion") + theme_bw()
```

# View Slope Posteriors

```{r, echo=FALSE}
ggplot(dat[dat$par %in% c("gamma"),],aes(x=estimate,fill=factor(Dispersion))) + geom_density(alpha=.4) +  theme_bw() + labs(fill="NB Size")
```

# Detection Probabilities

```{r, echo=FALSE}
ggplot(dat[dat$par %in% c("detect"),],aes(x=estimate,fill=factor(Dispersion))) + geom_histogram() + facet_wrap(~species,scales="free") + labs(fill="NB Dispersion")
```

#Tradeoff Between Alpha and Detect

```{r}
ad<-dat %>% filter(par %in% c("alpha","detect")) %>% select(-parameter)

ad<-dcast(ad,...~par,value.var="estimate")
ggplot(ad,aes(x=alpha,y=detect,col=Dispersion)) + geom_point() + scale_color_continuous(low="blue",high="red") + facet_wrap(~species,scales="free")  + labs(col="Size Parameter") 
```

# Predicted Relationship

```{r}
predfiles<-list.files("Dispersion/",pattern = "simdat",full.names = T)
preddata<-lapply(predfiles,read.csv,row.names=1)
names(preddata)<-str_extract(predfiles,"\\d+")
#first one is a decimal
names(preddata)[1]<-0.5
pdf<-melt(preddata,id.vars=colnames(preddata[[1]]))
```

```{r}
ggplot(pdf,aes(x=True_State,y=Occupancy,col=L1)) + geom_point(alpha=.5) + labs(col="Size Parameter")
```

#Posterior check values

```{r}
fitstat<-droplevels(dat[dat$par %in% c("fit","fitnew"),])
fitstat<-dcast(fitstat,Draw+Chain+Model+Dispersion~par,value.var="estimate")

#add 1:1 line
ymin<-round(min(c(fitstat$fit,fitstat$fitnew)))
ymax<-round(max(c(fitstat$fit,fitstat$fitnew)))
ab<-data.frame(x=ymin:ymax,y=ymin:ymax)
p<-ggplot(fitstat,aes(x=fit,y=fitnew)) + geom_point(aes(col=factor(Dispersion))) + theme_bw() + coord_equal()
p  + labs(x="Discrepancy of observed data",y="Discrepancy of replicated data",col="Model") + geom_line(data=ab,aes(x=x,y=y)) + ggtitle("Simulated Data")

```
