#!/bin/bash 

#Clone git repo
git clone https://github.com/bw4sz/Occupy.git

#collect password from cmd line
pas=$1

#set global 
git config --global email.address "benweinstein2010@gmail.com"
git config --global user.name "bw4sz"

#install packages
Rscript install.R

#Run source
Rscript Abunance_NegativeBinomial.Rmd

#add changes
git add --all

#commit changes
git commit -m "ec2 run complete"

#slightly tricky part, trying not to type this all in plain text.
git push "https://bw4sz:$pas@github.com/bw4sz/Occupy.git" master




